package com.tomsung.agdc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BeamStrength {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.BEAMDATA
	 * @mbg.generated
	 */
	private BigDecimal beamdata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.SYSTEMID
	 * @mbg.generated
	 */
	private Long systemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.CTRLID
	 * @mbg.generated
	 */
	private Integer ctrlid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.DEVICEID
	 * @mbg.generated
	 */
	private Integer deviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.DEVICETYPE
	 * @mbg.generated
	 */
	private Integer devicetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.TIME
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BEAMSTRENGTH.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.ID
	 * @return  the value of BEAMSTRENGTH.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.ID
	 * @param id  the value for BEAMSTRENGTH.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.FARMLANDID
	 * @return  the value of BEAMSTRENGTH.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.FARMLANDID
	 * @param farmlandid  the value for BEAMSTRENGTH.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.BEAMDATA
	 * @return  the value of BEAMSTRENGTH.BEAMDATA
	 * @mbg.generated
	 */
	public BigDecimal getBeamdata() {
		return beamdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.BEAMDATA
	 * @param beamdata  the value for BEAMSTRENGTH.BEAMDATA
	 * @mbg.generated
	 */
	public void setBeamdata(BigDecimal beamdata) {
		this.beamdata = beamdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.SYSTEMID
	 * @return  the value of BEAMSTRENGTH.SYSTEMID
	 * @mbg.generated
	 */
	public Long getSystemid() {
		return systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.SYSTEMID
	 * @param systemid  the value for BEAMSTRENGTH.SYSTEMID
	 * @mbg.generated
	 */
	public void setSystemid(Long systemid) {
		this.systemid = systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.CTRLID
	 * @return  the value of BEAMSTRENGTH.CTRLID
	 * @mbg.generated
	 */
	public Integer getCtrlid() {
		return ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.CTRLID
	 * @param ctrlid  the value for BEAMSTRENGTH.CTRLID
	 * @mbg.generated
	 */
	public void setCtrlid(Integer ctrlid) {
		this.ctrlid = ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.DEVICEID
	 * @return  the value of BEAMSTRENGTH.DEVICEID
	 * @mbg.generated
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.DEVICEID
	 * @param deviceid  the value for BEAMSTRENGTH.DEVICEID
	 * @mbg.generated
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.DEVICETYPE
	 * @return  the value of BEAMSTRENGTH.DEVICETYPE
	 * @mbg.generated
	 */
	public Integer getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.DEVICETYPE
	 * @param devicetype  the value for BEAMSTRENGTH.DEVICETYPE
	 * @mbg.generated
	 */
	public void setDevicetype(Integer devicetype) {
		this.devicetype = devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.TIME
	 * @return  the value of BEAMSTRENGTH.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.TIME
	 * @param time  the value for BEAMSTRENGTH.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BEAMSTRENGTH.REMARK
	 * @return  the value of BEAMSTRENGTH.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BEAMSTRENGTH.REMARK
	 * @param remark  the value for BEAMSTRENGTH.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BEAMSTRENGTH
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BeamStrength other = (BeamStrength) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getBeamdata() == null ? other.getBeamdata() == null
						: this.getBeamdata().equals(other.getBeamdata()))
				&& (this.getSystemid() == null ? other.getSystemid() == null
						: this.getSystemid().equals(other.getSystemid()))
				&& (this.getCtrlid() == null ? other.getCtrlid() == null : this.getCtrlid().equals(other.getCtrlid()))
				&& (this.getDeviceid() == null ? other.getDeviceid() == null
						: this.getDeviceid().equals(other.getDeviceid()))
				&& (this.getDevicetype() == null ? other.getDevicetype() == null
						: this.getDevicetype().equals(other.getDevicetype()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BEAMSTRENGTH
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getBeamdata() == null) ? 0 : getBeamdata().hashCode());
		result = prime * result + ((getSystemid() == null) ? 0 : getSystemid().hashCode());
		result = prime * result + ((getCtrlid() == null) ? 0 : getCtrlid().hashCode());
		result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
		result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}