package com.tomsung.agdc.domain;

public class CityKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CITY.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CITY.PROVINCEID
	 * @mbg.generated
	 */
	private Integer provinceid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CITY.ID
	 * @return  the value of CITY.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CITY.ID
	 * @param id  the value for CITY.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CITY.PROVINCEID
	 * @return  the value of CITY.PROVINCEID
	 * @mbg.generated
	 */
	public Integer getProvinceid() {
		return provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CITY.PROVINCEID
	 * @param provinceid  the value for CITY.PROVINCEID
	 * @mbg.generated
	 */
	public void setProvinceid(Integer provinceid) {
		this.provinceid = provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CITY
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CityKey other = (CityKey) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getProvinceid() == null ? other.getProvinceid() == null
						: this.getProvinceid().equals(other.getProvinceid()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CITY
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getProvinceid() == null) ? 0 : getProvinceid().hashCode());
		return result;
	}
}