package com.tomsung.agdc.domain;

public class City extends CityKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CITY.CITYNAME
	 * @mbg.generated
	 */
	private String cityname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CITY.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CITY.CITYNAME
	 * @return  the value of CITY.CITYNAME
	 * @mbg.generated
	 */
	public String getCityname() {
		return cityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CITY.CITYNAME
	 * @param cityname  the value for CITY.CITYNAME
	 * @mbg.generated
	 */
	public void setCityname(String cityname) {
		this.cityname = cityname == null ? null : cityname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CITY.REMARK
	 * @return  the value of CITY.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CITY.REMARK
	 * @param remark  the value for CITY.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CITY
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		City other = (City) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getProvinceid() == null ? other.getProvinceid() == null
						: this.getProvinceid().equals(other.getProvinceid()))
				&& (this.getCityname() == null ? other.getCityname() == null
						: this.getCityname().equals(other.getCityname()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CITY
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getProvinceid() == null) ? 0 : getProvinceid().hashCode());
		result = prime * result + ((getCityname() == null) ? 0 : getCityname().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}