package com.tomsung.agdc.domain;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Crop extends CropKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CROP.CROP_NAME
	 * @mbg.generated
	 */
	private String cropName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CROP.CROP_URL
	 * @mbg.generated
	 */
	private String cropUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CROP.CROP_NAME
	 * @return  the value of CROP.CROP_NAME
	 * @mbg.generated
	 */
	public String getCropName() {
		return cropName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CROP.CROP_NAME
	 * @param cropName  the value for CROP.CROP_NAME
	 * @mbg.generated
	 */
	public void setCropName(String cropName) {
		this.cropName = cropName == null ? null : cropName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CROP.CROP_URL
	 * @return  the value of CROP.CROP_URL
	 * @mbg.generated
	 */
	public String getCropUrl() {
		return cropUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CROP.CROP_URL
	 * @param cropUrl  the value for CROP.CROP_URL
	 * @mbg.generated
	 */
	public void setCropUrl(String cropUrl) {
		this.cropUrl = cropUrl == null ? null : cropUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Crop other = (Crop) that;
		return (this.getCropId() == null ? other.getCropId() == null : this.getCropId().equals(other.getCropId()))
				&& (this.getCropType() == null ? other.getCropType() == null
						: this.getCropType().equals(other.getCropType()))
				&& (this.getCropName() == null ? other.getCropName() == null
						: this.getCropName().equals(other.getCropName()))
				&& (this.getCropUrl() == null ? other.getCropUrl() == null
						: this.getCropUrl().equals(other.getCropUrl()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCropId() == null) ? 0 : getCropId().hashCode());
		result = prime * result + ((getCropType() == null) ? 0 : getCropType().hashCode());
		result = prime * result + ((getCropName() == null) ? 0 : getCropName().hashCode());
		result = prime * result + ((getCropUrl() == null) ? 0 : getCropUrl().hashCode());
		return result;
	}
}