package com.tomsung.agdc.domain;

public class CropType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CROPTYPE.CROP_TYPE
	 * @mbg.generated
	 */
	private Integer cropType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CROPTYPE.CROP_TYPE_NAME
	 * @mbg.generated
	 */
	private String cropTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CROPTYPE.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CROPTYPE.CROP_TYPE
	 * @return  the value of CROPTYPE.CROP_TYPE
	 * @mbg.generated
	 */
	public Integer getCropType() {
		return cropType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CROPTYPE.CROP_TYPE
	 * @param cropType  the value for CROPTYPE.CROP_TYPE
	 * @mbg.generated
	 */
	public void setCropType(Integer cropType) {
		this.cropType = cropType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CROPTYPE.CROP_TYPE_NAME
	 * @return  the value of CROPTYPE.CROP_TYPE_NAME
	 * @mbg.generated
	 */
	public String getCropTypeName() {
		return cropTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CROPTYPE.CROP_TYPE_NAME
	 * @param cropTypeName  the value for CROPTYPE.CROP_TYPE_NAME
	 * @mbg.generated
	 */
	public void setCropTypeName(String cropTypeName) {
		this.cropTypeName = cropTypeName == null ? null : cropTypeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CROPTYPE.REMARK
	 * @return  the value of CROPTYPE.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CROPTYPE.REMARK
	 * @param remark  the value for CROPTYPE.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROPTYPE
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CropType other = (CropType) that;
		return (this.getCropType() == null ? other.getCropType() == null
				: this.getCropType().equals(other.getCropType()))
				&& (this.getCropTypeName() == null ? other.getCropTypeName() == null
						: this.getCropTypeName().equals(other.getCropTypeName()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROPTYPE
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCropType() == null) ? 0 : getCropType().hashCode());
		result = prime * result + ((getCropTypeName() == null) ? 0 : getCropTypeName().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}