package com.tomsung.agdc.domain;

public class DeviceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DEVICE.SYSTEMID
	 * @mbg.generated
	 */
	private Long systemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DEVICE.CTRLID
	 * @mbg.generated
	 */
	private Integer ctrlid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DEVICE.DEVICEID
	 * @mbg.generated
	 */
	private Integer deviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DEVICE.DEVICETYPE
	 * @mbg.generated
	 */
	private Integer devicetype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVICE.SYSTEMID
	 * @return  the value of DEVICE.SYSTEMID
	 * @mbg.generated
	 */
	public Long getSystemid() {
		return systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVICE.SYSTEMID
	 * @param systemid  the value for DEVICE.SYSTEMID
	 * @mbg.generated
	 */
	public void setSystemid(Long systemid) {
		this.systemid = systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVICE.CTRLID
	 * @return  the value of DEVICE.CTRLID
	 * @mbg.generated
	 */
	public Integer getCtrlid() {
		return ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVICE.CTRLID
	 * @param ctrlid  the value for DEVICE.CTRLID
	 * @mbg.generated
	 */
	public void setCtrlid(Integer ctrlid) {
		this.ctrlid = ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVICE.DEVICEID
	 * @return  the value of DEVICE.DEVICEID
	 * @mbg.generated
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVICE.DEVICEID
	 * @param deviceid  the value for DEVICE.DEVICEID
	 * @mbg.generated
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DEVICE.DEVICETYPE
	 * @return  the value of DEVICE.DEVICETYPE
	 * @mbg.generated
	 */
	public Integer getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DEVICE.DEVICETYPE
	 * @param devicetype  the value for DEVICE.DEVICETYPE
	 * @mbg.generated
	 */
	public void setDevicetype(Integer devicetype) {
		this.devicetype = devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DeviceKey other = (DeviceKey) that;
		return (this.getSystemid() == null ? other.getSystemid() == null
				: this.getSystemid().equals(other.getSystemid()))
				&& (this.getCtrlid() == null ? other.getCtrlid() == null : this.getCtrlid().equals(other.getCtrlid()))
				&& (this.getDeviceid() == null ? other.getDeviceid() == null
						: this.getDeviceid().equals(other.getDeviceid()))
				&& (this.getDevicetype() == null ? other.getDevicetype() == null
						: this.getDevicetype().equals(other.getDevicetype()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSystemid() == null) ? 0 : getSystemid().hashCode());
		result = prime * result + ((getCtrlid() == null) ? 0 : getCtrlid().hashCode());
		result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
		result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
		return result;
	}
}