package com.tomsung.agdc.domain;

public class District extends DistrictKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DISTRICT.DISTRICTNAME
	 * @mbg.generated
	 */
	private String districtname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DISTRICT.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DISTRICT.DISTRICTNAME
	 * @return  the value of DISTRICT.DISTRICTNAME
	 * @mbg.generated
	 */
	public String getDistrictname() {
		return districtname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DISTRICT.DISTRICTNAME
	 * @param districtname  the value for DISTRICT.DISTRICTNAME
	 * @mbg.generated
	 */
	public void setDistrictname(String districtname) {
		this.districtname = districtname == null ? null : districtname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DISTRICT.REMARK
	 * @return  the value of DISTRICT.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DISTRICT.REMARK
	 * @param remark  the value for DISTRICT.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DISTRICT
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		District other = (District) that;
		return (this.getDistrictid() == null ? other.getDistrictid() == null
				: this.getDistrictid().equals(other.getDistrictid()))
				&& (this.getCityid() == null ? other.getCityid() == null : this.getCityid().equals(other.getCityid()))
				&& (this.getDistrictname() == null ? other.getDistrictname() == null
						: this.getDistrictname().equals(other.getDistrictname()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DISTRICT
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getDistrictid() == null) ? 0 : getDistrictid().hashCode());
		result = prime * result + ((getCityid() == null) ? 0 : getCityid().hashCode());
		result = prime * result + ((getDistrictname() == null) ? 0 : getDistrictname().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}