package com.tomsung.agdc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Expert {

    private Integer id;

    private Integer userid;

    private String mobilePhone;

    private String realname;

    private String expertType;

    private Integer evalutionCount;

    private Double avg;

    private String cropName;

    private Integer cropCount;

    private Integer replyCount;


    private String provinceName;

    private String cityName;

    private String districtName;

    private Date verifiedTime;

    private String address;

    private double add_x;

    private double add_y;

    private Integer liveness;

    private Integer typeCount;

    private Integer expertCount;

    private Integer replyCountByProvince;

    public String getAddress() {
        return address;
    }

    public double getAdd_x() {
        return add_x;
    }

    public double getAdd_y() {
        return add_y;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setAdd_x(double add_x) {
        this.add_x = add_x;
    }

    public void setAdd_y(double add_y) {
        this.add_y = add_y;
    }

    public void setReplyCountByProvince(Integer replyCountByProvince) {
        this.replyCountByProvince = replyCountByProvince;
    }

    public Integer getReplyCountByProvince() {
        return replyCountByProvince;
    }

    public Integer getExpertCount() {
        return expertCount;
    }

    public void setExpertCount(Integer expertCount) {
        this.expertCount = expertCount;
    }

    public Integer getLiveness() {
        return liveness;
    }

    public void setLiveness(Integer liveness) {
        this.liveness = liveness;
    }

    public Integer getTypeCount() {
        return typeCount;
    }

    public void setTypeCount(Integer typeCount) {
        this.typeCount = typeCount;
    }
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.ID
     *
     * @param id the value for EXPERT.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.USERID
     *
     * @return the value of EXPERT.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.USERID
     *
     * @param userid the value for EXPERT.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.MOBILE_PHONE
     *
     * @return the value of EXPERT.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.MOBILE_PHONE
     *
     * @param mobilePhone the value for EXPERT.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.REALNAME
     *
     * @return the value of EXPERT.REALNAME
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.REALNAME
     *
     * @param realname the value for EXPERT.REALNAME
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.EXPERT_TYPE
     *
     * @return the value of EXPERT.EXPERT_TYPE
     *
     * @mbg.generated
     */
    public String getExpertType() {
        return expertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.EXPERT_TYPE
     *
     * @param expertType the value for EXPERT.EXPERT_TYPE
     *
     * @mbg.generated
     */
    public void setExpertType(String expertType) {
        this.expertType = expertType == null ? null : expertType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.EVALUTION_COUNT
     *
     * @return the value of EXPERT.EVALUTION_COUNT
     *
     * @mbg.generated
     */
    public Integer getEvalutionCount() {
        return evalutionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.EVALUTION_COUNT
     *
     * @param evalutionCount the value for EXPERT.EVALUTION_COUNT
     *
     * @mbg.generated
     */
    public void setEvalutionCount(Integer evalutionCount) {
        this.evalutionCount = evalutionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.AVG
     *
     * @return the value of EXPERT.AVG
     *
     * @mbg.generated
     */
    public Double getAvg() {
        return avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.AVG
     *
     * @param avg the value for EXPERT.AVG
     *
     * @mbg.generated
     */
    public void setAvg(Double avg) {
        this.avg = avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.CROP_NAME
     *
     * @return the value of EXPERT.CROP_NAME
     *
     * @mbg.generated
     */
    public String getCropName() {
        return cropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.CROP_NAME
     *
     * @param cropName the value for EXPERT.CROP_NAME
     *
     * @mbg.generated
     */
    public void setCropName(String cropName) {
        this.cropName = cropName == null ? null : cropName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.CROP_COUNT
     *
     * @return the value of EXPERT.CROP_COUNT
     *
     * @mbg.generated
     */
    public Integer getCropCount() {
        return cropCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.CROP_COUNT
     *
     * @param cropCount the value for EXPERT.CROP_COUNT
     *
     * @mbg.generated
     */
    public void setCropCount(Integer cropCount) {
        this.cropCount = cropCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.REPLY_COUNT
     *
     * @return the value of EXPERT.REPLY_COUNT
     *
     * @mbg.generated
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.REPLY_COUNT
     *
     * @param replyCount the value for EXPERT.REPLY_COUNT
     *
     * @mbg.generated
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.PROVINCE_NAME
     *
     * @return the value of EXPERT.PROVINCE_NAME
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.PROVINCE_NAME
     *
     * @param provinceName the value for EXPERT.PROVINCE_NAME
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.CITY_NAME
     *
     * @return the value of EXPERT.CITY_NAME
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.CITY_NAME
     *
     * @param cityName the value for EXPERT.CITY_NAME
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.DISTRICT_NAME
     *
     * @return the value of EXPERT.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.DISTRICT_NAME
     *
     * @param districtName the value for EXPERT.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT.VERIFIED_TIME
     *
     * @return the value of EXPERT.VERIFIED_TIME
     *
     * @mbg.generated
     */
    public Date getVerifiedTime() {
        return verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT.VERIFIED_TIME
     *
     * @param verifiedTime the value for EXPERT.VERIFIED_TIME
     *
     * @mbg.generated
     */
    public void setVerifiedTime(Date verifiedTime) {
        this.verifiedTime = verifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Expert other = (Expert) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getMobilePhone() == null ? other.getMobilePhone() == null : this.getMobilePhone().equals(other.getMobilePhone()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getExpertType() == null ? other.getExpertType() == null : this.getExpertType().equals(other.getExpertType()))
            && (this.getEvalutionCount() == null ? other.getEvalutionCount() == null : this.getEvalutionCount().equals(other.getEvalutionCount()))
            && (this.getAvg() == null ? other.getAvg() == null : this.getAvg().equals(other.getAvg()))
            && (this.getCropName() == null ? other.getCropName() == null : this.getCropName().equals(other.getCropName()))
            && (this.getCropCount() == null ? other.getCropCount() == null : this.getCropCount().equals(other.getCropCount()))
            && (this.getReplyCount() == null ? other.getReplyCount() == null : this.getReplyCount().equals(other.getReplyCount()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getVerifiedTime() == null ? other.getVerifiedTime() == null : this.getVerifiedTime().equals(other.getVerifiedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getMobilePhone() == null) ? 0 : getMobilePhone().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getExpertType() == null) ? 0 : getExpertType().hashCode());
        result = prime * result + ((getEvalutionCount() == null) ? 0 : getEvalutionCount().hashCode());
        result = prime * result + ((getAvg() == null) ? 0 : getAvg().hashCode());
        result = prime * result + ((getCropName() == null) ? 0 : getCropName().hashCode());
        result = prime * result + ((getCropCount() == null) ? 0 : getCropCount().hashCode());
        result = prime * result + ((getReplyCount() == null) ? 0 : getReplyCount().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getVerifiedTime() == null) ? 0 : getVerifiedTime().hashCode());
        return result;
    }



}