package com.tomsung.agdc.domain;

import java.util.Date;

public class ExpertScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.EXPERT_ID
     *
     * @mbg.generated
     */
    private Integer expertId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.SCORE
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.COMMIT
     *
     * @mbg.generated
     */
    private String commit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.COMMIT_TIME
     *
     * @mbg.generated
     */
    private Date commitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPERT_SCORE.LABEL
     *
     * @mbg.generated
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.ID
     *
     * @return the value of EXPERT_SCORE.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.ID
     *
     * @param id the value for EXPERT_SCORE.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.EXPERT_ID
     *
     * @return the value of EXPERT_SCORE.EXPERT_ID
     *
     * @mbg.generated
     */
    public Integer getExpertId() {
        return expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.EXPERT_ID
     *
     * @param expertId the value for EXPERT_SCORE.EXPERT_ID
     *
     * @mbg.generated
     */
    public void setExpertId(Integer expertId) {
        this.expertId = expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.SCORE
     *
     * @return the value of EXPERT_SCORE.SCORE
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.SCORE
     *
     * @param score the value for EXPERT_SCORE.SCORE
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.COMMIT
     *
     * @return the value of EXPERT_SCORE.COMMIT
     *
     * @mbg.generated
     */
    public String getCommit() {
        return commit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.COMMIT
     *
     * @param commit the value for EXPERT_SCORE.COMMIT
     *
     * @mbg.generated
     */
    public void setCommit(String commit) {
        this.commit = commit == null ? null : commit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.COMMIT_TIME
     *
     * @return the value of EXPERT_SCORE.COMMIT_TIME
     *
     * @mbg.generated
     */
    public Date getCommitTime() {
        return commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.COMMIT_TIME
     *
     * @param commitTime the value for EXPERT_SCORE.COMMIT_TIME
     *
     * @mbg.generated
     */
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPERT_SCORE.LABEL
     *
     * @return the value of EXPERT_SCORE.LABEL
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPERT_SCORE.LABEL
     *
     * @param label the value for EXPERT_SCORE.LABEL
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExpertScore other = (ExpertScore) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getExpertId() == null ? other.getExpertId() == null : this.getExpertId().equals(other.getExpertId()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getCommit() == null ? other.getCommit() == null : this.getCommit().equals(other.getCommit()))
            && (this.getCommitTime() == null ? other.getCommitTime() == null : this.getCommitTime().equals(other.getCommitTime()))
            && (this.getLabel() == null ? other.getLabel() == null : this.getLabel().equals(other.getLabel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getExpertId() == null) ? 0 : getExpertId().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getCommit() == null) ? 0 : getCommit().hashCode());
        result = prime * result + ((getCommitTime() == null) ? 0 : getCommitTime().hashCode());
        result = prime * result + ((getLabel() == null) ? 0 : getLabel().hashCode());
        return result;
    }
}