package com.tomsung.agdc.domain;

import java.util.Date;

public class FertilizationDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FERTILIZATION_DETAIL.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FERTILIZATION_DETAIL.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FERTILIZATION_DETAIL.PRODUCT_ID
	 * @mbg.generated
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FERTILIZATION_DETAIL.USED_COUNT
	 * @mbg.generated
	 */
	private Integer usedCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FERTILIZATION_DETAIL.TIME
	 * @mbg.generated
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FERTILIZATION_DETAIL.ID
	 * @return  the value of FERTILIZATION_DETAIL.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FERTILIZATION_DETAIL.ID
	 * @param id  the value for FERTILIZATION_DETAIL.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FERTILIZATION_DETAIL.FARMLANDID
	 * @return  the value of FERTILIZATION_DETAIL.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FERTILIZATION_DETAIL.FARMLANDID
	 * @param farmlandid  the value for FERTILIZATION_DETAIL.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FERTILIZATION_DETAIL.PRODUCT_ID
	 * @return  the value of FERTILIZATION_DETAIL.PRODUCT_ID
	 * @mbg.generated
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FERTILIZATION_DETAIL.PRODUCT_ID
	 * @param productId  the value for FERTILIZATION_DETAIL.PRODUCT_ID
	 * @mbg.generated
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FERTILIZATION_DETAIL.USED_COUNT
	 * @return  the value of FERTILIZATION_DETAIL.USED_COUNT
	 * @mbg.generated
	 */
	public Integer getUsedCount() {
		return usedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FERTILIZATION_DETAIL.USED_COUNT
	 * @param usedCount  the value for FERTILIZATION_DETAIL.USED_COUNT
	 * @mbg.generated
	 */
	public void setUsedCount(Integer usedCount) {
		this.usedCount = usedCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FERTILIZATION_DETAIL.TIME
	 * @return  the value of FERTILIZATION_DETAIL.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FERTILIZATION_DETAIL.TIME
	 * @param time  the value for FERTILIZATION_DETAIL.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		FertilizationDetail other = (FertilizationDetail) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getProductId() == null ? other.getProductId() == null
						: this.getProductId().equals(other.getProductId()))
				&& (this.getUsedCount() == null ? other.getUsedCount() == null
						: this.getUsedCount().equals(other.getUsedCount()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
		result = prime * result + ((getUsedCount() == null) ? 0 : getUsedCount().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}
}