package com.tomsung.agdc.domain;

import java.util.Date;

public class OperateLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.FARMLAND_NAME
	 * @mbg.generated
	 */
	private String farmlandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.USEID
	 * @mbg.generated
	 */
	private Integer useid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.OPERATOR
	 * @mbg.generated
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.CONTENT
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.OPERSTATE
	 * @mbg.generated
	 */
	private String operstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.SYSTEMID
	 * @mbg.generated
	 */
	private Long systemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.CTRLID
	 * @mbg.generated
	 */
	private Integer ctrlid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.DEVICEID
	 * @mbg.generated
	 */
	private Integer deviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.DEVICETYPE
	 * @mbg.generated
	 */
	private Integer devicetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.DEIVCENAME
	 * @mbg.generated
	 */
	private String deivcename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.TIME
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATELOG.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.ID
	 * @return  the value of OPERATELOG.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.ID
	 * @param id  the value for OPERATELOG.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.FARMLANDID
	 * @return  the value of OPERATELOG.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.FARMLANDID
	 * @param farmlandid  the value for OPERATELOG.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.FARMLAND_NAME
	 * @return  the value of OPERATELOG.FARMLAND_NAME
	 * @mbg.generated
	 */
	public String getFarmlandName() {
		return farmlandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.FARMLAND_NAME
	 * @param farmlandName  the value for OPERATELOG.FARMLAND_NAME
	 * @mbg.generated
	 */
	public void setFarmlandName(String farmlandName) {
		this.farmlandName = farmlandName == null ? null : farmlandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.USEID
	 * @return  the value of OPERATELOG.USEID
	 * @mbg.generated
	 */
	public Integer getUseid() {
		return useid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.USEID
	 * @param useid  the value for OPERATELOG.USEID
	 * @mbg.generated
	 */
	public void setUseid(Integer useid) {
		this.useid = useid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.OPERATOR
	 * @return  the value of OPERATELOG.OPERATOR
	 * @mbg.generated
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.OPERATOR
	 * @param operator  the value for OPERATELOG.OPERATOR
	 * @mbg.generated
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.CONTENT
	 * @return  the value of OPERATELOG.CONTENT
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.CONTENT
	 * @param content  the value for OPERATELOG.CONTENT
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.OPERSTATE
	 * @return  the value of OPERATELOG.OPERSTATE
	 * @mbg.generated
	 */
	public String getOperstate() {
		return operstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.OPERSTATE
	 * @param operstate  the value for OPERATELOG.OPERSTATE
	 * @mbg.generated
	 */
	public void setOperstate(String operstate) {
		this.operstate = operstate == null ? null : operstate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.SYSTEMID
	 * @return  the value of OPERATELOG.SYSTEMID
	 * @mbg.generated
	 */
	public Long getSystemid() {
		return systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.SYSTEMID
	 * @param systemid  the value for OPERATELOG.SYSTEMID
	 * @mbg.generated
	 */
	public void setSystemid(Long systemid) {
		this.systemid = systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.CTRLID
	 * @return  the value of OPERATELOG.CTRLID
	 * @mbg.generated
	 */
	public Integer getCtrlid() {
		return ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.CTRLID
	 * @param ctrlid  the value for OPERATELOG.CTRLID
	 * @mbg.generated
	 */
	public void setCtrlid(Integer ctrlid) {
		this.ctrlid = ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.DEVICEID
	 * @return  the value of OPERATELOG.DEVICEID
	 * @mbg.generated
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.DEVICEID
	 * @param deviceid  the value for OPERATELOG.DEVICEID
	 * @mbg.generated
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.DEVICETYPE
	 * @return  the value of OPERATELOG.DEVICETYPE
	 * @mbg.generated
	 */
	public Integer getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.DEVICETYPE
	 * @param devicetype  the value for OPERATELOG.DEVICETYPE
	 * @mbg.generated
	 */
	public void setDevicetype(Integer devicetype) {
		this.devicetype = devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.DEIVCENAME
	 * @return  the value of OPERATELOG.DEIVCENAME
	 * @mbg.generated
	 */
	public String getDeivcename() {
		return deivcename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.DEIVCENAME
	 * @param deivcename  the value for OPERATELOG.DEIVCENAME
	 * @mbg.generated
	 */
	public void setDeivcename(String deivcename) {
		this.deivcename = deivcename == null ? null : deivcename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.TIME
	 * @return  the value of OPERATELOG.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.TIME
	 * @param time  the value for OPERATELOG.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATELOG.REMARK
	 * @return  the value of OPERATELOG.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATELOG.REMARK
	 * @param remark  the value for OPERATELOG.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		OperateLog other = (OperateLog) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getFarmlandName() == null ? other.getFarmlandName() == null
						: this.getFarmlandName().equals(other.getFarmlandName()))
				&& (this.getUseid() == null ? other.getUseid() == null : this.getUseid().equals(other.getUseid()))
				&& (this.getOperator() == null ? other.getOperator() == null
						: this.getOperator().equals(other.getOperator()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()))
				&& (this.getOperstate() == null ? other.getOperstate() == null
						: this.getOperstate().equals(other.getOperstate()))
				&& (this.getSystemid() == null ? other.getSystemid() == null
						: this.getSystemid().equals(other.getSystemid()))
				&& (this.getCtrlid() == null ? other.getCtrlid() == null : this.getCtrlid().equals(other.getCtrlid()))
				&& (this.getDeviceid() == null ? other.getDeviceid() == null
						: this.getDeviceid().equals(other.getDeviceid()))
				&& (this.getDevicetype() == null ? other.getDevicetype() == null
						: this.getDevicetype().equals(other.getDevicetype()))
				&& (this.getDeivcename() == null ? other.getDeivcename() == null
						: this.getDeivcename().equals(other.getDeivcename()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getFarmlandName() == null) ? 0 : getFarmlandName().hashCode());
		result = prime * result + ((getUseid() == null) ? 0 : getUseid().hashCode());
		result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
		result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
		result = prime * result + ((getOperstate() == null) ? 0 : getOperstate().hashCode());
		result = prime * result + ((getSystemid() == null) ? 0 : getSystemid().hashCode());
		result = prime * result + ((getCtrlid() == null) ? 0 : getCtrlid().hashCode());
		result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
		result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
		result = prime * result + ((getDeivcename() == null) ? 0 : getDeivcename().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}