package com.tomsung.agdc.domain;

import java.util.Date;

public class OperateDevLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.SYSTEMID
	 * @mbg.generated
	 */
	private Long systemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.CTRLID
	 * @mbg.generated
	 */
	private Integer ctrlid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.DEVICEID
	 * @mbg.generated
	 */
	private Integer deviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.DEVICETYPE
	 * @mbg.generated
	 */
	private Integer devicetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.DEIVCENAME
	 * @mbg.generated
	 */
	private String deivcename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.OPER
	 * @mbg.generated
	 */
	private String oper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column OPERATE_DEV_LOG.TIME
	 * @mbg.generated
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.ID
	 * @return  the value of OPERATE_DEV_LOG.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.ID
	 * @param id  the value for OPERATE_DEV_LOG.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.FARMLANDID
	 * @return  the value of OPERATE_DEV_LOG.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.FARMLANDID
	 * @param farmlandid  the value for OPERATE_DEV_LOG.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.SYSTEMID
	 * @return  the value of OPERATE_DEV_LOG.SYSTEMID
	 * @mbg.generated
	 */
	public Long getSystemid() {
		return systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.SYSTEMID
	 * @param systemid  the value for OPERATE_DEV_LOG.SYSTEMID
	 * @mbg.generated
	 */
	public void setSystemid(Long systemid) {
		this.systemid = systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.CTRLID
	 * @return  the value of OPERATE_DEV_LOG.CTRLID
	 * @mbg.generated
	 */
	public Integer getCtrlid() {
		return ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.CTRLID
	 * @param ctrlid  the value for OPERATE_DEV_LOG.CTRLID
	 * @mbg.generated
	 */
	public void setCtrlid(Integer ctrlid) {
		this.ctrlid = ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.DEVICEID
	 * @return  the value of OPERATE_DEV_LOG.DEVICEID
	 * @mbg.generated
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.DEVICEID
	 * @param deviceid  the value for OPERATE_DEV_LOG.DEVICEID
	 * @mbg.generated
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.DEVICETYPE
	 * @return  the value of OPERATE_DEV_LOG.DEVICETYPE
	 * @mbg.generated
	 */
	public Integer getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.DEVICETYPE
	 * @param devicetype  the value for OPERATE_DEV_LOG.DEVICETYPE
	 * @mbg.generated
	 */
	public void setDevicetype(Integer devicetype) {
		this.devicetype = devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.DEIVCENAME
	 * @return  the value of OPERATE_DEV_LOG.DEIVCENAME
	 * @mbg.generated
	 */
	public String getDeivcename() {
		return deivcename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.DEIVCENAME
	 * @param deivcename  the value for OPERATE_DEV_LOG.DEIVCENAME
	 * @mbg.generated
	 */
	public void setDeivcename(String deivcename) {
		this.deivcename = deivcename == null ? null : deivcename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.OPER
	 * @return  the value of OPERATE_DEV_LOG.OPER
	 * @mbg.generated
	 */
	public String getOper() {
		return oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.OPER
	 * @param oper  the value for OPERATE_DEV_LOG.OPER
	 * @mbg.generated
	 */
	public void setOper(String oper) {
		this.oper = oper == null ? null : oper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column OPERATE_DEV_LOG.TIME
	 * @return  the value of OPERATE_DEV_LOG.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column OPERATE_DEV_LOG.TIME
	 * @param time  the value for OPERATE_DEV_LOG.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATE_DEV_LOG
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		OperateDevLog other = (OperateDevLog) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getSystemid() == null ? other.getSystemid() == null
						: this.getSystemid().equals(other.getSystemid()))
				&& (this.getCtrlid() == null ? other.getCtrlid() == null : this.getCtrlid().equals(other.getCtrlid()))
				&& (this.getDeviceid() == null ? other.getDeviceid() == null
						: this.getDeviceid().equals(other.getDeviceid()))
				&& (this.getDevicetype() == null ? other.getDevicetype() == null
						: this.getDevicetype().equals(other.getDevicetype()))
				&& (this.getDeivcename() == null ? other.getDeivcename() == null
						: this.getDeivcename().equals(other.getDeivcename()))
				&& (this.getOper() == null ? other.getOper() == null : this.getOper().equals(other.getOper()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATE_DEV_LOG
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getSystemid() == null) ? 0 : getSystemid().hashCode());
		result = prime * result + ((getCtrlid() == null) ? 0 : getCtrlid().hashCode());
		result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
		result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
		result = prime * result + ((getDeivcename() == null) ? 0 : getDeivcename().hashCode());
		result = prime * result + ((getOper() == null) ? 0 : getOper().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}
}