package com.tomsung.agdc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Plan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.PLANID
	 * @mbg.generated
	 */
	private Integer planid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.PLANTYPE
	 * @mbg.generated
	 */
	private Integer plantype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.STARTTIME
	 * @mbg.generated
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.ENDTIME
	 * @mbg.generated
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PLAN.SUMMATION
	 * @mbg.generated
	 */
	private BigDecimal summation;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.PLANID
	 * @return  the value of PLAN.PLANID
	 * @mbg.generated
	 */
	public Integer getPlanid() {
		return planid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.PLANID
	 * @param planid  the value for PLAN.PLANID
	 * @mbg.generated
	 */
	public void setPlanid(Integer planid) {
		this.planid = planid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.FARMLANDID
	 * @return  the value of PLAN.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.FARMLANDID
	 * @param farmlandid  the value for PLAN.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.PLANTYPE
	 * @return  the value of PLAN.PLANTYPE
	 * @mbg.generated
	 */
	public Integer getPlantype() {
		return plantype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.PLANTYPE
	 * @param plantype  the value for PLAN.PLANTYPE
	 * @mbg.generated
	 */
	public void setPlantype(Integer plantype) {
		this.plantype = plantype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.STARTTIME
	 * @return  the value of PLAN.STARTTIME
	 * @mbg.generated
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.STARTTIME
	 * @param starttime  the value for PLAN.STARTTIME
	 * @mbg.generated
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.ENDTIME
	 * @return  the value of PLAN.ENDTIME
	 * @mbg.generated
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.ENDTIME
	 * @param endtime  the value for PLAN.ENDTIME
	 * @mbg.generated
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PLAN.SUMMATION
	 * @return  the value of PLAN.SUMMATION
	 * @mbg.generated
	 */
	public BigDecimal getSummation() {
		return summation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PLAN.SUMMATION
	 * @param summation  the value for PLAN.SUMMATION
	 * @mbg.generated
	 */
	public void setSummation(BigDecimal summation) {
		this.summation = summation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PLAN
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Plan other = (Plan) that;
		return (this.getPlanid() == null ? other.getPlanid() == null : this.getPlanid().equals(other.getPlanid()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getPlantype() == null ? other.getPlantype() == null
						: this.getPlantype().equals(other.getPlantype()))
				&& (this.getStarttime() == null ? other.getStarttime() == null
						: this.getStarttime().equals(other.getStarttime()))
				&& (this.getEndtime() == null ? other.getEndtime() == null
						: this.getEndtime().equals(other.getEndtime()))
				&& (this.getSummation() == null ? other.getSummation() == null
						: this.getSummation().equals(other.getSummation()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PLAN
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPlanid() == null) ? 0 : getPlanid().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getPlantype() == null) ? 0 : getPlantype().hashCode());
		result = prime * result + ((getStarttime() == null) ? 0 : getStarttime().hashCode());
		result = prime * result + ((getEndtime() == null) ? 0 : getEndtime().hashCode());
		result = prime * result + ((getSummation() == null) ? 0 : getSummation().hashCode());
		return result;
	}
}