package com.tomsung.agdc.domain;

public class ProductWithBLOBs extends Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT.SUB_IMAGES
	 * @mbg.generated
	 */
	private String subImages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT.DETAIL
	 * @mbg.generated
	 */
	private String detail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT.SUB_IMAGES
	 * @return  the value of PRODUCT.SUB_IMAGES
	 * @mbg.generated
	 */
	public String getSubImages() {
		return subImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT.SUB_IMAGES
	 * @param subImages  the value for PRODUCT.SUB_IMAGES
	 * @mbg.generated
	 */
	public void setSubImages(String subImages) {
		this.subImages = subImages == null ? null : subImages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT.DETAIL
	 * @return  the value of PRODUCT.DETAIL
	 * @mbg.generated
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT.DETAIL
	 * @param detail  the value for PRODUCT.DETAIL
	 * @mbg.generated
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ProductWithBLOBs other = (ProductWithBLOBs) that;
		return (this.getProductId() == null ? other.getProductId() == null
				: this.getProductId().equals(other.getProductId()))
				&& (this.getCategoryId() == null ? other.getCategoryId() == null
						: this.getCategoryId().equals(other.getCategoryId()))
				&& (this.getCompanyId() == null ? other.getCompanyId() == null
						: this.getCompanyId().equals(other.getCompanyId()))
				&& (this.getProductSn() == null ? other.getProductSn() == null
						: this.getProductSn().equals(other.getProductSn()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getSubtitle() == null ? other.getSubtitle() == null
						: this.getSubtitle().equals(other.getSubtitle()))
				&& (this.getMainImage() == null ? other.getMainImage() == null
						: this.getMainImage().equals(other.getMainImage()))
				&& (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
				&& (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getSubImages() == null ? other.getSubImages() == null
						: this.getSubImages().equals(other.getSubImages()))
				&& (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
		result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
		result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
		result = prime * result + ((getProductSn() == null) ? 0 : getProductSn().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getSubtitle() == null) ? 0 : getSubtitle().hashCode());
		result = prime * result + ((getMainImage() == null) ? 0 : getMainImage().hashCode());
		result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
		result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getSubImages() == null) ? 0 : getSubImages().hashCode());
		result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
		return result;
	}
}