package com.tomsung.agdc.domain;

import java.util.Date;

public class ProductCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.PARENT_ID
	 * @mbg.generated
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.NAME
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.SORT_ORDER
	 * @mbg.generated
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.CREATE_TIME
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_CATEGORY.UPDATE_TIME
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.ID
	 * @return  the value of PRODUCT_CATEGORY.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.ID
	 * @param id  the value for PRODUCT_CATEGORY.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.PARENT_ID
	 * @return  the value of PRODUCT_CATEGORY.PARENT_ID
	 * @mbg.generated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.PARENT_ID
	 * @param parentId  the value for PRODUCT_CATEGORY.PARENT_ID
	 * @mbg.generated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.NAME
	 * @return  the value of PRODUCT_CATEGORY.NAME
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.NAME
	 * @param name  the value for PRODUCT_CATEGORY.NAME
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.SORT_ORDER
	 * @return  the value of PRODUCT_CATEGORY.SORT_ORDER
	 * @mbg.generated
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.SORT_ORDER
	 * @param sortOrder  the value for PRODUCT_CATEGORY.SORT_ORDER
	 * @mbg.generated
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.CREATE_TIME
	 * @return  the value of PRODUCT_CATEGORY.CREATE_TIME
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.CREATE_TIME
	 * @param createTime  the value for PRODUCT_CATEGORY.CREATE_TIME
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_CATEGORY.UPDATE_TIME
	 * @return  the value of PRODUCT_CATEGORY.UPDATE_TIME
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_CATEGORY.UPDATE_TIME
	 * @param updateTime  the value for PRODUCT_CATEGORY.UPDATE_TIME
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ProductCategory other = (ProductCategory) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getSortOrder() == null ? other.getSortOrder() == null
						: this.getSortOrder().equals(other.getSortOrder()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}