package com.tomsung.agdc.domain;

import java.util.Date;

public class ProficientCropKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFICIENT_CROP.USERID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFICIENT_CROP.CROP_ID
     *
     * @mbg.generated
     */
    private Integer cropId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFICIENT_CROP.USERID
     *
     * @return the value of PROFICIENT_CROP.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFICIENT_CROP.USERID
     *
     * @param userid the value for PROFICIENT_CROP.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFICIENT_CROP.CROP_ID
     *
     * @return the value of PROFICIENT_CROP.CROP_ID
     *
     * @mbg.generated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFICIENT_CROP.CROP_ID
     *
     * @param cropId the value for PROFICIENT_CROP.CROP_ID
     *
     * @mbg.generated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFICIENT_CROP
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProficientCropKey other = (ProficientCropKey) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getCropId() == null ? other.getCropId() == null : this.getCropId().equals(other.getCropId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFICIENT_CROP
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getCropId() == null) ? 0 : getCropId().hashCode());
        return result;
    }
    
    private User user;
    private Crop crop;
    private QuestionReplyRecord questionReplyRecord;

    private Date time;
    private Integer expertCount;

    public Date getTime() {
        return time;
    }

    public Integer getExpertCount() {
        return expertCount;
    }
    public void setTime(Date time) {
        this.time = time;
    }

    public void setExpertCount(Integer expertCount) {
        this.expertCount = expertCount;
    }
    public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Crop getCrop() {
		return crop;
	}

	public void setCrop(Crop crop) {
		this.crop = crop;
	}

	public QuestionReplyRecord getQuestionReplyRecord() {
		return questionReplyRecord;
	}

	public void setQuestionReplyRecord(QuestionReplyRecord questionReplyRecord) {
		this.questionReplyRecord = questionReplyRecord;
	}
    
}