package com.tomsung.agdc.domain;

public class Province {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROVINCE.PROVINCEID
	 * @mbg.generated
	 */
	private Integer provinceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROVINCE.PROVINCENAME
	 * @mbg.generated
	 */
	private String provincename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROVINCE.UNITNAME
	 * @mbg.generated
	 */
	private String unitname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROVINCE.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROVINCE.PROVINCEID
	 * @return  the value of PROVINCE.PROVINCEID
	 * @mbg.generated
	 */
	public Integer getProvinceid() {
		return provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROVINCE.PROVINCEID
	 * @param provinceid  the value for PROVINCE.PROVINCEID
	 * @mbg.generated
	 */
	public void setProvinceid(Integer provinceid) {
		this.provinceid = provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROVINCE.PROVINCENAME
	 * @return  the value of PROVINCE.PROVINCENAME
	 * @mbg.generated
	 */
	public String getProvincename() {
		return provincename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROVINCE.PROVINCENAME
	 * @param provincename  the value for PROVINCE.PROVINCENAME
	 * @mbg.generated
	 */
	public void setProvincename(String provincename) {
		this.provincename = provincename == null ? null : provincename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROVINCE.UNITNAME
	 * @return  the value of PROVINCE.UNITNAME
	 * @mbg.generated
	 */
	public String getUnitname() {
		return unitname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROVINCE.UNITNAME
	 * @param unitname  the value for PROVINCE.UNITNAME
	 * @mbg.generated
	 */
	public void setUnitname(String unitname) {
		this.unitname = unitname == null ? null : unitname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROVINCE.REMARK
	 * @return  the value of PROVINCE.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROVINCE.REMARK
	 * @param remark  the value for PROVINCE.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROVINCE
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Province other = (Province) that;
		return (this.getProvinceid() == null ? other.getProvinceid() == null
				: this.getProvinceid().equals(other.getProvinceid()))
				&& (this.getProvincename() == null ? other.getProvincename() == null
						: this.getProvincename().equals(other.getProvincename()))
				&& (this.getUnitname() == null ? other.getUnitname() == null
						: this.getUnitname().equals(other.getUnitname()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROVINCE
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getProvinceid() == null) ? 0 : getProvinceid().hashCode());
		result = prime * result + ((getProvincename() == null) ? 0 : getProvincename().hashCode());
		result = prime * result + ((getUnitname() == null) ? 0 : getUnitname().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}