package com.tomsung.agdc.domain;

import java.util.Date;

public class QuestionReplyRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUESTION_REPLY_RECORD.USERID
	 * @mbg.generated
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUESTION_REPLY_RECORD.QUESTION_COUNT
	 * @mbg.generated
	 */
	private Integer questionCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUESTION_REPLY_RECORD.REPLY_COUNT
	 * @mbg.generated
	 */
	private Integer replyCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QUESTION_REPLY_RECORD.TIME
	 * @mbg.generated
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUESTION_REPLY_RECORD.USERID
	 * @return  the value of QUESTION_REPLY_RECORD.USERID
	 * @mbg.generated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUESTION_REPLY_RECORD.USERID
	 * @param userid  the value for QUESTION_REPLY_RECORD.USERID
	 * @mbg.generated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUESTION_REPLY_RECORD.QUESTION_COUNT
	 * @return  the value of QUESTION_REPLY_RECORD.QUESTION_COUNT
	 * @mbg.generated
	 */
	public Integer getQuestionCount() {
		return questionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUESTION_REPLY_RECORD.QUESTION_COUNT
	 * @param questionCount  the value for QUESTION_REPLY_RECORD.QUESTION_COUNT
	 * @mbg.generated
	 */
	public void setQuestionCount(Integer questionCount) {
		this.questionCount = questionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUESTION_REPLY_RECORD.REPLY_COUNT
	 * @return  the value of QUESTION_REPLY_RECORD.REPLY_COUNT
	 * @mbg.generated
	 */
	public Integer getReplyCount() {
		return replyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUESTION_REPLY_RECORD.REPLY_COUNT
	 * @param replyCount  the value for QUESTION_REPLY_RECORD.REPLY_COUNT
	 * @mbg.generated
	 */
	public void setReplyCount(Integer replyCount) {
		this.replyCount = replyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QUESTION_REPLY_RECORD.TIME
	 * @return  the value of QUESTION_REPLY_RECORD.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QUESTION_REPLY_RECORD.TIME
	 * @param time  the value for QUESTION_REPLY_RECORD.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		QuestionReplyRecord other = (QuestionReplyRecord) that;
		return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
				&& (this.getQuestionCount() == null ? other.getQuestionCount() == null
						: this.getQuestionCount().equals(other.getQuestionCount()))
				&& (this.getReplyCount() == null ? other.getReplyCount() == null
						: this.getReplyCount().equals(other.getReplyCount()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
		result = prime * result + ((getQuestionCount() == null) ? 0 : getQuestionCount().hashCode());
		result = prime * result + ((getReplyCount() == null) ? 0 : getReplyCount().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}
}