package com.tomsung.agdc.domain;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.QUESTION_ID
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.IS_ADOPT
     *
     * @mbg.generated
     */
    private Integer isAdopt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.REPLY_TIME
     *
     * @mbg.generated
     */
    private Date replyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.ID
     *
     * @return the value of REPLY.ID
     *
     * @mbg.generated
     */
    private Integer replyCount;

    public Integer getReplyCount() {
        return replyCount;
    }

    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.ID
     *
     * @param id the value for REPLY.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.QUESTION_ID
     *
     * @return the value of REPLY.QUESTION_ID
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.QUESTION_ID
     *
     * @param questionId the value for REPLY.QUESTION_ID
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.USER_ID
     *
     * @return the value of REPLY.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.USER_ID
     *
     * @param userId the value for REPLY.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.CONTENT
     *
     * @return the value of REPLY.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.CONTENT
     *
     * @param content the value for REPLY.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.IS_ADOPT
     *
     * @return the value of REPLY.IS_ADOPT
     *
     * @mbg.generated
     */
    public Integer getIsAdopt() {
        return isAdopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.IS_ADOPT
     *
     * @param isAdopt the value for REPLY.IS_ADOPT
     *
     * @mbg.generated
     */
    public void setIsAdopt(Integer isAdopt) {
        this.isAdopt = isAdopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.REPLY_TIME
     *
     * @return the value of REPLY.REPLY_TIME
     *
     * @mbg.generated
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.REPLY_TIME
     *
     * @param replyTime the value for REPLY.REPLY_TIME
     *
     * @mbg.generated
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reply other = (Reply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuestionId() == null ? other.getQuestionId() == null : this.getQuestionId().equals(other.getQuestionId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getIsAdopt() == null ? other.getIsAdopt() == null : this.getIsAdopt().equals(other.getIsAdopt()))
            && (this.getReplyTime() == null ? other.getReplyTime() == null : this.getReplyTime().equals(other.getReplyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuestionId() == null) ? 0 : getQuestionId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getIsAdopt() == null) ? 0 : getIsAdopt().hashCode());
        result = prime * result + ((getReplyTime() == null) ? 0 : getReplyTime().hashCode());
        return result;
    }
}