package com.tomsung.agdc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class SaleDetail {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.ID
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.PROVINCE_ID
     *
     * @mbg.generated
     */
    private Integer provinceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.CITY_ID
     *
     * @mbg.generated
     */
    private Integer cityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.DISTRICT_ID
     *
     * @mbg.generated
     */
    private Integer districtId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.PRODUCT_ID
     *
     * @mbg.generated
     */
    private Integer productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.SALE_TIME
     *
     * @mbg.generated
     */
    private Date saleTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.SALE_COUNT
     *
     * @mbg.generated
     */
    private BigDecimal saleCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_DETAIL.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.ID
     *
     * @return the value of SALE_DETAIL.ID
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.ID
     *
     * @param id the value for SALE_DETAIL.ID
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.USER_ID
     *
     * @return the value of SALE_DETAIL.USER_ID
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.USER_ID
     *
     * @param userId the value for SALE_DETAIL.USER_ID
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.PROVINCE_ID
     *
     * @return the value of SALE_DETAIL.PROVINCE_ID
     * @mbg.generated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.PROVINCE_ID
     *
     * @param provinceId the value for SALE_DETAIL.PROVINCE_ID
     * @mbg.generated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.CITY_ID
     *
     * @return the value of SALE_DETAIL.CITY_ID
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.CITY_ID
     *
     * @param cityId the value for SALE_DETAIL.CITY_ID
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.DISTRICT_ID
     *
     * @return the value of SALE_DETAIL.DISTRICT_ID
     * @mbg.generated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.DISTRICT_ID
     *
     * @param districtId the value for SALE_DETAIL.DISTRICT_ID
     * @mbg.generated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.PRODUCT_ID
     *
     * @return the value of SALE_DETAIL.PRODUCT_ID
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.PRODUCT_ID
     *
     * @param productId the value for SALE_DETAIL.PRODUCT_ID
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.SALE_TIME
     *
     * @return the value of SALE_DETAIL.SALE_TIME
     * @mbg.generated
     */
    public Date getSaleTime() {
        return saleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.SALE_TIME
     *
     * @param saleTime the value for SALE_DETAIL.SALE_TIME
     * @mbg.generated
     */
    public void setSaleTime(Date saleTime) {
        this.saleTime = saleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.SALE_COUNT
     *
     * @return the value of SALE_DETAIL.SALE_COUNT
     * @mbg.generated
     */
    public BigDecimal getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.SALE_COUNT
     *
     * @param saleCount the value for SALE_DETAIL.SALE_COUNT
     * @mbg.generated
     */
    public void setSaleCount(BigDecimal saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_DETAIL.ADDRESS
     *
     * @return the value of SALE_DETAIL.ADDRESS
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_DETAIL.ADDRESS
     *
     * @param address the value for SALE_DETAIL.ADDRESS
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SaleDetail other = (SaleDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getProvinceId() == null ? other.getProvinceId() == null
                : this.getProvinceId().equals(other.getProvinceId()))
                && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
                && (this.getDistrictId() == null ? other.getDistrictId() == null
                : this.getDistrictId().equals(other.getDistrictId()))
                && (this.getProductId() == null ? other.getProductId() == null
                : this.getProductId().equals(other.getProductId()))
                && (this.getSaleTime() == null ? other.getSaleTime() == null
                : this.getSaleTime().equals(other.getSaleTime()))
                && (this.getSaleCount() == null ? other.getSaleCount() == null
                : this.getSaleCount().equals(other.getSaleCount()))
                && (this.getAddress() == null ? other.getAddress() == null
                : this.getAddress().equals(other.getAddress()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getDistrictId() == null) ? 0 : getDistrictId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSaleTime() == null) ? 0 : getSaleTime().hashCode());
        result = prime * result + ((getSaleCount() == null) ? 0 : getSaleCount().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        return result;
    }

    private User user;
    private Province province;
    private City city;
    private District district;
    private Product product;
    private ProductCompany productCompany;

    public ProductCompany getProductCompany() {
        return productCompany;
    }

    public void setProductCompany(ProductCompany productCompany) {
        this.productCompany = productCompany;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Province getProvince() {
        return province;
    }

    public void setProvince(Province province) {
        this.province = province;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public District getDistrict() {
        return district;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

}