package com.tomsung.agdc.domain;

import java.util.Date;
import java.util.List;

public class Suggestion {

    private Integer id;

    private String name;

    private Integer productId;

    private Integer collectionCount;

    private Integer viewingCount;

    private Date publishTime;

    private Date createTime;

    private Date updateTime;

    private double sales;

    private double prepaid;

    public double getPrepaid() {
        return prepaid;
    }

    public void setPrepaid(double prepaid) {
        this.prepaid = prepaid;
    }

    public double getSales() {
        return sales;
    }

    public void setSales(double sales) {
        this.sales = sales;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.name
     *
     * @return the value of SUGGESTION.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.name
     *
     * @param name the value for SUGGESTION.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.product_id
     *
     * @return the value of SUGGESTION.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.product_id
     *
     * @param productId the value for SUGGESTION.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.collection_count
     *
     * @return the value of SUGGESTION.collection_count
     *
     * @mbg.generated
     */
    public Integer getCollectionCount() {
        return collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.collection_count
     *
     * @param collectionCount the value for SUGGESTION.collection_count
     *
     * @mbg.generated
     */
    public void setCollectionCount(Integer collectionCount) {
        this.collectionCount = collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.viewing_count
     *
     * @return the value of SUGGESTION.viewing_count
     *
     * @mbg.generated
     */
    public Integer getViewingCount() {
        return viewingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.viewing_count
     *
     * @param viewingCount the value for SUGGESTION.viewing_count
     *
     * @mbg.generated
     */
    public void setViewingCount(Integer viewingCount) {
        this.viewingCount = viewingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.publish_time
     *
     * @return the value of SUGGESTION.publish_time
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.publish_time
     *
     * @param publishTime the value for SUGGESTION.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.create_time
     *
     * @return the value of SUGGESTION.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.create_time
     *
     * @param createTime the value for SUGGESTION.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUGGESTION.update_time
     *
     * @return the value of SUGGESTION.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUGGESTION.update_time
     *
     * @param updateTime the value for SUGGESTION.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Suggestion other = (Suggestion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getCollectionCount() == null ? other.getCollectionCount() == null : this.getCollectionCount().equals(other.getCollectionCount()))
            && (this.getViewingCount() == null ? other.getViewingCount() == null : this.getViewingCount().equals(other.getViewingCount()))
            && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getCollectionCount() == null) ? 0 : getCollectionCount().hashCode());
        result = prime * result + ((getViewingCount() == null) ? 0 : getViewingCount().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}