package com.tomsung.agdc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Temperature {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.FARMLANDID
	 * @mbg.generated
	 */
	private Integer farmlandid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.TEMPDATA
	 * @mbg.generated
	 */
	private BigDecimal tempdata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.SYSTEMID
	 * @mbg.generated
	 */
	private Long systemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.CTRLID
	 * @mbg.generated
	 */
	private Integer ctrlid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.DEVICEID
	 * @mbg.generated
	 */
	private Integer deviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.DEVICETYPE
	 * @mbg.generated
	 */
	private Integer devicetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.TIME
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEMPERATURE.REMARK
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.ID
	 * @return  the value of TEMPERATURE.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.ID
	 * @param id  the value for TEMPERATURE.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.FARMLANDID
	 * @return  the value of TEMPERATURE.FARMLANDID
	 * @mbg.generated
	 */
	public Integer getFarmlandid() {
		return farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.FARMLANDID
	 * @param farmlandid  the value for TEMPERATURE.FARMLANDID
	 * @mbg.generated
	 */
	public void setFarmlandid(Integer farmlandid) {
		this.farmlandid = farmlandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.TEMPDATA
	 * @return  the value of TEMPERATURE.TEMPDATA
	 * @mbg.generated
	 */
	public BigDecimal getTempdata() {
		return tempdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.TEMPDATA
	 * @param tempdata  the value for TEMPERATURE.TEMPDATA
	 * @mbg.generated
	 */
	public void setTempdata(BigDecimal tempdata) {
		this.tempdata = tempdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.SYSTEMID
	 * @return  the value of TEMPERATURE.SYSTEMID
	 * @mbg.generated
	 */
	public Long getSystemid() {
		return systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.SYSTEMID
	 * @param systemid  the value for TEMPERATURE.SYSTEMID
	 * @mbg.generated
	 */
	public void setSystemid(Long systemid) {
		this.systemid = systemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.CTRLID
	 * @return  the value of TEMPERATURE.CTRLID
	 * @mbg.generated
	 */
	public Integer getCtrlid() {
		return ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.CTRLID
	 * @param ctrlid  the value for TEMPERATURE.CTRLID
	 * @mbg.generated
	 */
	public void setCtrlid(Integer ctrlid) {
		this.ctrlid = ctrlid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.DEVICEID
	 * @return  the value of TEMPERATURE.DEVICEID
	 * @mbg.generated
	 */
	public Integer getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.DEVICEID
	 * @param deviceid  the value for TEMPERATURE.DEVICEID
	 * @mbg.generated
	 */
	public void setDeviceid(Integer deviceid) {
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.DEVICETYPE
	 * @return  the value of TEMPERATURE.DEVICETYPE
	 * @mbg.generated
	 */
	public Integer getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.DEVICETYPE
	 * @param devicetype  the value for TEMPERATURE.DEVICETYPE
	 * @mbg.generated
	 */
	public void setDevicetype(Integer devicetype) {
		this.devicetype = devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.TIME
	 * @return  the value of TEMPERATURE.TIME
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.TIME
	 * @param time  the value for TEMPERATURE.TIME
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEMPERATURE.REMARK
	 * @return  the value of TEMPERATURE.REMARK
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEMPERATURE.REMARK
	 * @param remark  the value for TEMPERATURE.REMARK
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Temperature other = (Temperature) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getFarmlandid() == null ? other.getFarmlandid() == null
						: this.getFarmlandid().equals(other.getFarmlandid()))
				&& (this.getTempdata() == null ? other.getTempdata() == null
						: this.getTempdata().equals(other.getTempdata()))
				&& (this.getSystemid() == null ? other.getSystemid() == null
						: this.getSystemid().equals(other.getSystemid()))
				&& (this.getCtrlid() == null ? other.getCtrlid() == null : this.getCtrlid().equals(other.getCtrlid()))
				&& (this.getDeviceid() == null ? other.getDeviceid() == null
						: this.getDeviceid().equals(other.getDeviceid()))
				&& (this.getDevicetype() == null ? other.getDevicetype() == null
						: this.getDevicetype().equals(other.getDevicetype()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getFarmlandid() == null) ? 0 : getFarmlandid().hashCode());
		result = prime * result + ((getTempdata() == null) ? 0 : getTempdata().hashCode());
		result = prime * result + ((getSystemid() == null) ? 0 : getSystemid().hashCode());
		result = prime * result + ((getCtrlid() == null) ? 0 : getCtrlid().hashCode());
		result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
		result = prime * result + ((getDevicetype() == null) ? 0 : getDevicetype().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}