package com.tomsung.agdc.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.Crop;
import com.tomsung.agdc.domain.CropKey;

import java.util.List;

@Mapper
@Component
public interface CropMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(CropKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	int insert(Crop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	int insertSelective(Crop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	Crop selectByPrimaryKey(CropKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Crop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CROP
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Crop record);


	List<Crop> selectByBlockId(Integer blockId);
}