package com.tomsung.agdc.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.CyclePlanDetail;
@Mapper
@Component
public interface CyclePlanDetailMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	int insert(CyclePlanDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	int insertSelective(CyclePlanDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	CyclePlanDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CyclePlanDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CYCLEPLAN_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CyclePlanDetail record);

	List<CyclePlanDetail> selectCyclePlanDetail(@Param(value = "planId")Integer planId);

}