package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Device;
import com.tomsung.agdc.domain.DeviceKey;
import com.tomsung.agdc.vo.SensorVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DeviceKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    Device selectByPrimaryKey(DeviceKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table DEVICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Device record);

    List<Device> selectDevices(@Param(value = "farmlandId") Integer farmlandId);

    Integer count(List<Byte> deviceType);

    List<SensorVo> selectSensorCountByKey(List key);

    Integer selectDeviceCount(@Param("date") Date date);
}