package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.ExpertScore;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.Date;

@Mapper
@Component
public interface ExpertScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    int insert(ExpertScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    int insertSelective(ExpertScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    ExpertScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExpertScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT_SCORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpertScore record);

    int selectCommitCount(Date date);
}