package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Expert;
import com.tomsung.agdc.vo.ExpertListItemVO;
import com.tomsung.agdc.vo.RankVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface ExpertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    int insert(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    int insertSelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    Expert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPERT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Expert record);

    //专家总数
    int selectExpertCount(Date date);

    //覆盖区域数
    int selectDistrictCount();
    //月新增区域
    int selectMonthDistrictCount(Date date);

    //专家回答问题总数
    int selectReplyCount();
    //专家被评价次数
    int selectEvalutionCount();
    //专家活跃度排名
    List<Expert> selectExpertLiveness();
    //专家评分排名
    List<Expert> selectExpertEvalution();
    //专家类型及其数量
    List<Expert> selectExpertType();
    //每个省份的专家信息
    List<Expert> selectExpertInfoByProvince();
    //每个专家的信息
    List<Expert> selectExpertInfo();

    int updateLongtitude(@Param(value="id") Integer id,@Param(value="lon") Object lon,@Param(value="lat") Object lat);

    List<ExpertListItemVO> selectList(@Param("keyword") String keyword);

    List<RankVo> selectLivenessTop10();

    List<RankVo> selectGradeTop10();
}