package com.tomsung.agdc.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.FertilizationDetail;
@Mapper
@Component
public interface FertilizationDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	int insert(FertilizationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	int insertSelective(FertilizationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	FertilizationDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(FertilizationDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FERTILIZATION_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKey(FertilizationDetail record);
}