package com.tomsung.agdc.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.Humidity;
@Mapper
@Component
public interface HumidityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	int insert(Humidity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	int insertSelective(Humidity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	Humidity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Humidity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HUMIDITY
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Humidity record);

	List<Humidity> selectHimidity(
			@Param(value = "farmlandid")Integer farmlandId, 
			@Param(value = "beginTime")Date beginTime, 
			@Param(value = "endTime")Date endTime, 
			@Param(value = "devicetype")int devType);
}