package com.tomsung.agdc.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.OperateLog;
@Mapper
@Component
public interface OperateLogMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	int insert(OperateLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	int insertSelective(OperateLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	OperateLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OperateLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table OPERATELOG
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OperateLog record);

	List<OperateLog> setAllLog();

	Integer selectActivityCount(Date date);

	//签约用户的人均活跃度
	Integer selectContractLiveness(Date time);
	//非签约用户的人均活跃度
	Integer selectNoContractLiveness(Date time);



}