package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Order;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    int selectOrderCount(Date date);

    int selectMountOfMoney(Date date);

    int selectMountOfWeight(Date date);

    int selectDistrictCount();

    int selectMonthDistrictCount(Date date);

    List<Order> selectOrderGroupByDistrict(@Param("beginTime") Date beginTime, @Param("endTime") Date endTime);

    int selectOrderCountByTime(Date time);

    List<Order> selectDistrictOrderInfo();

    Integer selectCountByCompanyAndTime(@Param("companyId") String companyId, @Param("time") Date beginTime);

    List<String> selectCityByCompany(@Param("companyId") String companyId);

    Integer selectCountByCompany(@Param("companyId") Integer companyId);

    Integer selectMoneyAvg();
}