package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.ProductCompany;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface ProductCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    int insert(ProductCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    int insertSelective(ProductCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    ProductCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_COMPANY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCompany record);

	List<String> selectCompany();
	List<Integer> selectCompanyId();
	List<String> selectCompanyCity();
}