package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Production;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    Production selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Production record);

    int selectProductionCount(Date date);

    List<Production> selectProduct();

    int selectOrderCountGroupByProduct(Integer id);
}