package com.tomsung.agdc.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.ProductCategory;
@Mapper
@Component
public interface ProductCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	int insert(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	int insertSelective(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	ProductCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ProductCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_CATEGORY
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ProductCategory record);
}