package com.tomsung.agdc.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.ProficientCropKey;

@Mapper
@Component
public interface ProficientCropMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFICIENT_CROP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ProficientCropKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFICIENT_CROP
     *
     * @mbg.generated
     */
    int insert(ProficientCropKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFICIENT_CROP
     *
     * @mbg.generated
     */
    int insertSelective(ProficientCropKey record);

	List<ProficientCropKey> selectAllProficients();

	int selectCropCount();

	int selectMonthCropCount(Date date);

	List<ProficientCropKey> selectConsistOfCrop();
    
}