package com.tomsung.agdc.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.QuestionReplyRecord;
@Mapper
@Component
public interface QuestionReplyRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	int insert(QuestionReplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	int insertSelective(QuestionReplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	QuestionReplyRecord selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(QuestionReplyRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QUESTION_REPLY_RECORD
	 * @mbg.generated
	 */
	int updateByPrimaryKey(QuestionReplyRecord record);
}