package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Reply;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.Date;

@Mapper
@Component
public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    Reply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPLY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Reply record);

    int selectReplyCount(Date date);

    int selectAdoptCount(Date date);
}