package com.tomsung.agdc.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.SaleDetail;
@Mapper
@Component
public interface SaleDetailMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	int insert(SaleDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	int insertSelective(SaleDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	SaleDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SaleDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SALE_DETAIL
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SaleDetail record);

	List<SaleDetail> selectAllSaleDetails();

	List<SaleDetail> selectSaleDetails(
			@Param(value="provinceId")Integer provinceId, 
			@Param(value="cityId")Integer cityId, 
			@Param(value="districtId")Integer districtId);

	List<SaleDetail> selectPointSaleDetails();

	List<SaleDetail> selectSaleDetailsByUser(@Param(value="userId")Integer userId);
}