package com.tomsung.agdc.mapper;

import com.tomsung.agdc.domain.Suggestion;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface SuggestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    int insert(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    int insertSelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    Suggestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUGGESTION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Suggestion record);

    int selectSuggestionCount(Date date);

    List<Suggestion> selectSales();

    double selectSum();
    double selectPrepaidSum();

    List<Suggestion> selectLikeName(@Param("name") String name);
}