package com.tomsung.agdc.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import com.tomsung.agdc.domain.Temperature;
@Mapper
@Component
public interface TemperatureMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	int insert(Temperature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	int insertSelective(Temperature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	Temperature selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Temperature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TEMPERATURE
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Temperature record);

	List<Temperature> selectTemperature(
			@Param(value = "farmlandid")Integer farmlandid,
			@Param(value = "beginTime")Date beginTime, 
			@Param(value = "endTime")Date endTime, 
			@Param(value = "devicetype")int devicetype);
}